#!/bin/bash
#SBATCH --job-name=l_re
#SBATCH --nodes 1
#SBATCH --cpus-per-task 10
#SBATCH --signal=USR1@90
#SBATCH --requeue
#SBATCH --mem=60GB
#SBATCH --time=72:00:00
#SBATCH --partition=dev

export HABITAT_SIM_LOG=quiet

MAIN_ADDR=$(scontrol show hostnames "${SLURM_JOB_NODELIST}" | head -n 1)
echo $MAIN_ADDR
echo $EXP_NAME

set -x
srun python -u -m habitat_baselines.run  \
    --exp-config ${EXP_CONFIG} --run-type train TENSORBOARD_DIR "tb/${EXP_NAME}/" \
    VIDEO_DIR video_dir/${EXP_NAME}/ EVAL_CKPT_PATH_DIR "data/new_checkpoints/${EXP_NAME}/" \
    CHECKPOINT_FOLDER "data/new_checkpoints/${EXP_NAME}/" TASK_CONFIG.GYM.OBS_KEYS ${OBS_KEYS} \
    TASK_CONFIG.SIMULATOR.HEAD_DEPTH_SENSOR.WIDTH ${VIS_RES} TASK_CONFIG.SIMULATOR.HEAD_DEPTH_SENSOR.HEIGHT ${VIS_RES} \
    TASK_CONFIG.SIMULATOR.HEAD_RGB_SENSOR.WIDTH ${VIS_RES} TASK_CONFIG.SIMULATOR.HEAD_RGB_SENSOR.HEIGHT ${VIS_RES} \
    TASK_CONFIG.SIMULATOR.ARM_DEPTH_SENSOR.WIDTH ${VIS_RES} TASK_CONFIG.SIMULATOR.ARM_DEPTH_SENSOR.HEIGHT ${VIS_RES} \
    TASK_CONFIG.SIMULATOR.ARM_RGB_SENSOR.WIDTH ${VIS_RES} TASK_CONFIG.SIMULATOR.ARM_RGB_SENSOR.HEIGHT ${VIS_RES} \
    SENSORS ${SENSORS} TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS ${SENSORS} NUM_ENVIRONMENTS ${ENVS} TASK_CONFIG.DATASET.DATA_PATH ${DATA_PATH}
